name: CI - Tests and Code Style

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
      NODE_ENV: development

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v2

      # 2. Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3. Clean System Cache and MongoDB Binaries
      - name: Clean System Cache and MongoDB Binaries
        run: |
          rm -rf /home/runner/.cache/mongodb-binaries || true
          sudo apt-get update
          sudo apt-get install -y libssl1.1 || echo "Libssl1.1 could not be installed."  # Actualizamos a libssl1.1

      # 4. Clean Node.js and Jest Cache
      - name: Clean Node.js and Jest Cache
        run: |
          npm cache clean --force
          npx jest --clearCache

      # 5. Install dependencies (fresh install)
      - name: Install Dependencies
        run: npm ci

      # 6. Build the application (if applicable)
      - name: Build Application
        run: |
          if [ -f "package.json" ] && [ -f "webpack.config.js" ]; then
            npm run build
          else
            echo "No build step required. Skipping..."
          fi

      # 7. Run Jest tests
      - name: Run Tests
        run: npm test

      # 8. Run code style checks
      - name: Run Code Style Checks
        run: npm run code-style-check
