name: CI - Tests and Code Style

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test-vitest:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NO_REPLY_EMAIL: ${{ secrets.NO_REPLY_EMAIL }}
      INFO_EMAIL: ${{ secrets.AUTH_EMAIL }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      API_URL_LOCAL: ${{ secrets.API_URL_LOCAL }}
      API_URL_HEROKU: ${{ secrets.API_URL_HEROKU }}
      DONNA_VINO_WEB_LOCAL: ${{ secrets.DONNA_VINO_WEB_LOCAL }}
      DONNA_VINO_WEB_HEROKU: ${{ secrets.DONNA_VINO_WEB_HEROKU }}
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: |
          if [ -f "package.json" ] && [ -f "webpack.config.js" ]; then
            npm run build
          else
            echo "No build step required. Skipping..."
          fi

      - name: Clean MongoDB lock
        run: rm -rf ~/.cache/mongodb-binaries/*.lock

      - name: Run Vitest Tests
        run: npm run test -- --no-watch

      - name: Run Code Style Checks
        run: npm run code-style-check
